!=======================================================================
! Generated by  : PSCAD v4.6.2.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_XPI     ! 'Proportional-Integral Controller /w Interpolation'
!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    EMTDC_XONDLAY  ! 'Delay Function with Interpolation'
      REAL    REALPOLE      ! Real Pole
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  Breaker, IT_1, Trip_Signal, IT_2
      INTEGER  BRK_Batt, IT_3, Cmd_Main_HSCB
      INTEGER  Cmd_PreCh, Cmd_ResetPreCh
      REAL     I_Cap_Discharge, V_Touch, Pa, Pb
      REAL     Pc, Ia_RMS, Ib_RMS, Ic_RMS, RT_1
      REAL     I_Fault, RT_2, Va, Vb, Vc, RT_3
      REAL     RT_4, RT_5, RT_6, RT_7, RT_8, RT_9
      REAL     g2, g4, RT_10, RT_11, RT_12, RT_13
      REAL     RT_14, RT_15, RT_16, RT_17, RT_18
      REAL     RT_19, g3, RT_20, g1, I_Battery
      REAL     RT_21, RT_22, RT_23, V_DC_Link
      REAL     RT_24, RT_25, RT_26, RT_27, RT_28
      REAL     RT_29, RT_30, RT_31, RT_32, RT_33
      REAL     I_ext, RT_34, I_Train

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)
      REAL     RVD2_3(2), RVD2_4(2), RVD1_2
      REAL     RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 9
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 54
      IPGB      = NPGB
      NPGB      = NPGB + 20
      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 57
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      Breaker  = STOI(ISTOI + 1)
      I_Cap_Discharge = STOF(ISTOF + 1)
      V_Touch  = STOF(ISTOF + 2)
      Pa       = STOF(ISTOF + 3)
      Pb       = STOF(ISTOF + 4)
      Pc       = STOF(ISTOF + 5)
      Ia_RMS   = STOF(ISTOF + 6)
      Ib_RMS   = STOF(ISTOF + 7)
      Ic_RMS   = STOF(ISTOF + 8)
      RT_1     = STOF(ISTOF + 9)
      I_Fault  = STOF(ISTOF + 10)
      RT_2     = STOF(ISTOF + 11)
      Va       = STOF(ISTOF + 12)
      Vb       = STOF(ISTOF + 13)
      Vc       = STOF(ISTOF + 14)
      IT_1     = STOI(ISTOI + 2)
      Trip_Signal = STOI(ISTOI + 3)
      IT_2     = STOI(ISTOI + 4)
      RT_3     = STOF(ISTOF + 15)
      RT_4     = STOF(ISTOF + 16)
      RT_5     = STOF(ISTOF + 17)
      RT_6     = STOF(ISTOF + 18)
      RT_7     = STOF(ISTOF + 19)
      RT_8     = STOF(ISTOF + 20)
      RT_9     = STOF(ISTOF + 21)
      g2       = STOF(ISTOF + 22)
      g4       = STOF(ISTOF + 23)
      RT_10    = STOF(ISTOF + 24)
      RT_11    = STOF(ISTOF + 25)
      RT_12    = STOF(ISTOF + 26)
      RT_13    = STOF(ISTOF + 27)
      RT_14    = STOF(ISTOF + 28)
      RT_15    = STOF(ISTOF + 29)
      RT_16    = STOF(ISTOF + 30)
      RT_17    = STOF(ISTOF + 31)
      RT_18    = STOF(ISTOF + 32)
      RT_19    = STOF(ISTOF + 33)
      g3       = STOF(ISTOF + 34)
      RT_20    = STOF(ISTOF + 35)
      g1       = STOF(ISTOF + 36)
      I_Battery = STOF(ISTOF + 37)
      RT_21    = STOF(ISTOF + 38)
      BRK_Batt = STOI(ISTOI + 5)
      RT_22    = STOF(ISTOF + 39)
      RT_23    = STOF(ISTOF + 40)
      V_DC_Link = STOF(ISTOF + 41)
      RT_24    = STOF(ISTOF + 42)
      RT_25    = STOF(ISTOF + 43)
      IT_3     = STOI(ISTOI + 6)
      RT_26    = STOF(ISTOF + 44)
      Cmd_Main_HSCB = STOI(ISTOI + 7)
      RT_27    = STOF(ISTOF + 45)
      RT_28    = STOF(ISTOF + 46)
      RT_29    = STOF(ISTOF + 47)
      RT_30    = STOF(ISTOF + 48)
      Cmd_PreCh = STOI(ISTOI + 8)
      RT_31    = STOF(ISTOF + 49)
      RT_32    = STOF(ISTOF + 50)
      RT_33    = STOF(ISTOF + 51)
      I_ext    = STOF(ISTOF + 52)
      RT_34    = STOF(ISTOF + 53)
      Cmd_ResetPreCh = STOI(ISTOI + 9)
      I_Train  = STOF(ISTOF + 54)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 180:[const] Real Constant 

      RT_12 = 3.1

! 190:[const] Real Constant 

      RT_16 = 3.0

! 200:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1164716438)
      CALL E_XSGEN1_EXE(1,1000.0,RVD2_1)
      RT_20 = RVD2_1(1)

! 210:[sumjct] Summing/Differencing Junctions 
      RT_14 = - RT_16 + V_DC_Link

! 220:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RT_15 = EMTDC_XPI(0,1.0,0.05,0.05,0.95,RVD1_1,RVD2_1)

! 230:[const] Real Constant 

      RT_1 = 5.0

! 240:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,903945719)
      CALL E_XSGEN1_EXE(1,1000.0,RVD2_1)
      RT_19 = RVD2_1(1)

! 250:[time-sig] Output of Simulation Time 
      RT_22 = TIME

! 260:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         Breaker = 1
      ELSE
         Breaker = 1
         IF ( TIME .GE. 1.0 ) Breaker = (1-1)
         IF ( TIME .GE. 1.2 ) Breaker = 1
      ENDIF

! 270:[const] Real Constant 

      RT_23 = 1.5

! 280:[const] Real Constant 

      RT_10 = 2.9

! 290:[const] Real Constant 

      RT_24 = 2.8

! 300:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1637781821)
      CALL E_XSGEN1_EXE(1,1000.0,RVD2_1)
      RT_7 = RVD2_1(1)

! 310:[const] Real Constant 

      RT_32 = 8.0

! 320:[const] Real Constant 

      RT_26 = 0.0

! 330:[const] Real Constant 

      RT_4 = 3.0

! 340:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_4 - V_DC_Link

! 350:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_5
      RVD2_1(2) = 0.0
      RT_6 = EMTDC_XPI(0,1.0,0.05,0.0,2.0,RVD1_1,RVD2_1)

! 360:[sumjct] Summing/Differencing Junctions 
      RT_21 = + RT_6 - I_Battery

! 380:[time-sig] Output of Simulation Time 
      RT_27 = TIME

! 390:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,496891745)
      CALL E_XSGEN1_EXE(1,1000.0,RVD2_1)
      RT_8 = RVD2_1(1)

! 400:[const] Real Constant 

      RT_28 = 0.005

! 410:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,V_DC_Link,RT_12,1.0,0.0,0.0,RVD2_1)
      RT_13 = RVD2_1(1)

! 420:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_Fault,RT_1,1.0,0.0,0.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 430:[mult] Multiplier 
      RT_18 = RT_15 * RT_13

! 440:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(NINT(RT_2))
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.02,RVD2_1,RVD2_2)
      IT_2 = NINT(RVD2_2(1))

! 450:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_22,RT_23,1.0,0.0,0.0,RVD2_1)
      RT_3 = RVD2_1(1)

! 460:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,V_DC_Link,RT_10,0.0,0.0,1.0,RVD2_1)
      RT_11 = RVD2_1(1)

! 470:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,V_DC_Link,RT_24,1.0,0.0,0.0,RVD2_1)
      RT_25 = RVD2_1(1)

! 480:[flip_flop] Flip-Flop and latches /w Interpolation 
      RVD2_1(1) = RT_25
      RVD2_2(1) = RT_26
      RVD2_3(1) = 1.0
      RVD2_1(2) = 0.0
      RVD2_2(2) = 0.0
      RVD2_3(2) = 0.0
!
      CALL E_XFLIP1_EXE(RVD2_1,RVD2_2,RVD2_3,RVD2_4)
      Cmd_ResetPreCh = NINT(RVD2_4(1))
      IT_3 = 1 - Cmd_ResetPreCh

! 490:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_21
      RVD2_1(2) = 0.0
      RT_17 = EMTDC_XPI(0,0.5,0.01,0.05,0.95,RVD1_1,RVD2_1)

! 500:[div] Divider 
!
      IF (ABS(RT_33) .LT. 1.0E-10) THEN
         IF (RT_33 .LT. 0.0)  THEN
            RT_31 = -1.0E10 * RT_32
         ELSE
            RT_31 =  1.0E10 * RT_32
         ENDIF
      ELSE
         RT_31 = RT_32 / RT_33
      ENDIF
!

! 510:[mult] Multiplier 
      RT_34 = RT_31 * REAL(Cmd_ResetPreCh)

! 520:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_27,RT_28,1.0,0.0,0.0,RVD2_1)
      RT_29 = RVD2_1(1)

! 530:[sumjct] Summing/Differencing Junctions 
      RT_30 = + RT_29 - REAL(Cmd_ResetPreCh)

! 540:[mult] Multiplier 
      RT_9 = RT_11 * RT_17

! 550:[flip_flop] Flip-Flop and latches /w Interpolation 
      RVD2_1(1) = REAL(IT_2)
      RVD2_2(1) = RT_3
      RVD2_3(1) = 1.0
      RVD2_1(2) = 0.0
      RVD2_2(2) = 0.0
      RVD2_3(2) = 0.0
!
      CALL E_XFLIP1_EXE(RVD2_1,RVD2_2,RVD2_3,RVD2_4)
      Trip_Signal = NINT(RVD2_4(1))
      IT_1 = 1 - Trip_Signal

! 560:[inv] Interpolated Logic Inverter 
      IF (NINT(RT_30) .NE. 0) THEN
         Cmd_PreCh = 0
      ELSE
         Cmd_PreCh = 1
      ENDIF

! 570:[realpole] Real Pole 
!  Real_Pole
      I_ext = REALPOLE(0,1,0,1.0,1.0,RT_34,0.0,-10.0,10.0)

! 580:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_9,RT_8,1.0,0.0,0.0,RVD2_1)
      g2 = RVD2_1(1)

! 590:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_9,RT_7,1.0,0.0,0.0,RVD2_1)
      g4 = RVD2_1(1)

! 600:[inv] Interpolated Logic Inverter 
      IF (Cmd_ResetPreCh .NE. 0) THEN
         Cmd_Main_HSCB = 0
      ELSE
         Cmd_Main_HSCB = 1
      ENDIF

! 610:[inv] Interpolated Logic Inverter 
      IF (IT_1 .NE. 0) THEN
         BRK_Batt = 0
      ELSE
         BRK_Batt = 1
      ENDIF

! 620:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_18,RT_19,1.0,0.0,0.0,RVD2_1)
      g3 = RVD2_1(1)

! 630:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_18,RT_20,1.0,0.0,0.0,RVD2_1)
      g1 = RVD2_1(1)

! 640:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1140137438)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+9), NINT(g2), 0.0)

! 650:[breaker1] Single Phase Breaker 'BRK_Batt'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+50),0.005,1000000.0,1,NINT(1.0-&
     &REAL(BRK_Batt)))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+50),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,415900577,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+50),SS(1)))

! 660:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,2010922438)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+8), NINT(g4), 0.0)

! 670:[breaker1] Single Phase Breaker 'Breaker'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+5),0.005,1000000.0,1,NINT(1.0-R&
     &EAL(Breaker)))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+5),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,926414752,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+5),SS(1)))

! 680:[pgb] Output Channel 'g4'

      PGB(IPGB+9) = g4

! 690:[pgb] Output Channel 'g2'

      PGB(IPGB+10) = g2

! 710:[pgb] Output Channel 'Ext Current Control'

      PGB(IPGB+12) = I_ext

! 720:[pgb] Output Channel 'g3'

      PGB(IPGB+13) = g3

! 730:[pgb] Output Channel 'g1'

      PGB(IPGB+14) = g1

! 740:[src_ccin_1] Current Source 'I_Train'
      CCBR( (IBRCH(1)+2),SS(1)) = I_ext
      IF (TIMEZERO) CCBRD( (IBRCH(1)+2),SS(1)) = I_ext

! 760:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,716549863)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+7), NINT(g3), 0.0)

! 770:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,988036300)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+3), NINT(g1), 0.0)

! 810:[breaker3] 3 Phase Breaker 'Trip_Signal'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+35),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(Trip_Signal)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+36),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(Trip_Signal)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+37),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(Trip_Signal)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+35),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+36),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+37),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1235735319,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1235735319,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1235735319,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+35),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+36),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+37),SS(1)))

! 840:[breaker1] Single Phase Breaker 'Cmd_PreCh'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+10),0.005,1000000.0,1,NINT(1.0-&
     &REAL(Cmd_PreCh)))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,69880901,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))

! 850:[breaker1] Single Phase Breaker 'Cmd_Main_HSCB'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+11),0.005,1000000.0,1,NINT(1.0-&
     &REAL(Cmd_Main_HSCB)))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+11),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1927417187,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+11),SS(1)))

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,719893317)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+38), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1830649735)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+40), 1, 0.0)

! 1:[source_3] Three Phase Voltage Source Model 2 'AC Grid'
! Three Phase Source: AC Grid  Type: Ideal
!  
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = 0.0*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+17), (IBRCH(1)+18), (IBRCH(1)+&
     &19), RVD1_4, .TRUE., RVD1_1 , RVD1_2, RVD1_3)
!

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1967063505)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+42), 1, 0.0)

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 'T32'
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((IXFMR + 1),(IXFMR + 2),(IXFMR + 3), (IBRCH(1)+26),&
     & (IBRCH(1)+27), (IBRCH(1)+28), (IBRCH(1)+29), (IBRCH(1)+30), (IBRC&
     &H(1)+31),0,0,0,0,0,0,SS(1),0,1.0,0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,651248504)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+44), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1244104662)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+46), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1233889562)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+48), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,397305173)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+13), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,91867956)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+14), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1549103707)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+15), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1101419496)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+16), 1, 0.0)

! 1:[battery] Generic battery model 'Battery Bank'
      IVD1_1=NSTORF
      CALL COMPONENT_ID(ICALL_NO,54542169)
      CALL BATTERYCOEFF1_EXE(SS(1), (IBRCH(1)+12))

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOI(ISTOI + 1) = Breaker
      STOF(ISTOF + 1) = I_Cap_Discharge
      STOF(ISTOF + 2) = V_Touch
      STOF(ISTOF + 3) = Pa
      STOF(ISTOF + 4) = Pb
      STOF(ISTOF + 5) = Pc
      STOF(ISTOF + 6) = Ia_RMS
      STOF(ISTOF + 7) = Ib_RMS
      STOF(ISTOF + 8) = Ic_RMS
      STOF(ISTOF + 9) = RT_1
      STOF(ISTOF + 10) = I_Fault
      STOF(ISTOF + 11) = RT_2
      STOF(ISTOF + 12) = Va
      STOF(ISTOF + 13) = Vb
      STOF(ISTOF + 14) = Vc
      STOI(ISTOI + 2) = IT_1
      STOI(ISTOI + 3) = Trip_Signal
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 15) = RT_3
      STOF(ISTOF + 16) = RT_4
      STOF(ISTOF + 17) = RT_5
      STOF(ISTOF + 18) = RT_6
      STOF(ISTOF + 19) = RT_7
      STOF(ISTOF + 20) = RT_8
      STOF(ISTOF + 21) = RT_9
      STOF(ISTOF + 22) = g2
      STOF(ISTOF + 23) = g4
      STOF(ISTOF + 24) = RT_10
      STOF(ISTOF + 25) = RT_11
      STOF(ISTOF + 26) = RT_12
      STOF(ISTOF + 27) = RT_13
      STOF(ISTOF + 28) = RT_14
      STOF(ISTOF + 29) = RT_15
      STOF(ISTOF + 30) = RT_16
      STOF(ISTOF + 31) = RT_17
      STOF(ISTOF + 32) = RT_18
      STOF(ISTOF + 33) = RT_19
      STOF(ISTOF + 34) = g3
      STOF(ISTOF + 35) = RT_20
      STOF(ISTOF + 36) = g1
      STOF(ISTOF + 37) = I_Battery
      STOF(ISTOF + 38) = RT_21
      STOI(ISTOI + 5) = BRK_Batt
      STOF(ISTOF + 39) = RT_22
      STOF(ISTOF + 40) = RT_23
      STOF(ISTOF + 41) = V_DC_Link
      STOF(ISTOF + 42) = RT_24
      STOF(ISTOF + 43) = RT_25
      STOI(ISTOI + 6) = IT_3
      STOF(ISTOF + 44) = RT_26
      STOI(ISTOI + 7) = Cmd_Main_HSCB
      STOF(ISTOF + 45) = RT_27
      STOF(ISTOF + 46) = RT_28
      STOF(ISTOF + 47) = RT_29
      STOF(ISTOF + 48) = RT_30
      STOI(ISTOI + 8) = Cmd_PreCh
      STOF(ISTOF + 49) = RT_31
      STOF(ISTOF + 50) = RT_32
      STOF(ISTOF + 51) = RT_33
      STOF(ISTOF + 52) = I_ext
      STOF(ISTOF + 53) = RT_34
      STOI(ISTOI + 9) = Cmd_ResetPreCh
      STOF(ISTOF + 54) = I_Train


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    PQVI1PH       ! P,Q,V,I measurement in a 1p branch
      REAL    RMS3          ! 'Instantaneous RMS Measurement'
      REAL    LIMIT         ! Hard Limiter
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1, NT_6, NT_12, NT_13, NT_14

! Control Signals
      REAL     I_Cap_Discharge, V_Touch, Pa, Pb
      REAL     Pc, Ia_RMS, Ib_RMS, Ic_RMS, RT_1
      REAL     I_Fault, Va, Vb, Vc, RT_4, RT_10
      REAL     RT_12, RT_16, I_Battery, RT_23
      REAL     V_DC_Link, RT_24, RT_26, RT_28
      REAL     RT_32, RT_33, I_Train

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 20
      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 57
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      I_Cap_Discharge = STOF(ISTOF + 1)
      V_Touch  = STOF(ISTOF + 2)
      Pa       = STOF(ISTOF + 3)
      Pb       = STOF(ISTOF + 4)
      Pc       = STOF(ISTOF + 5)
      Ia_RMS   = STOF(ISTOF + 6)
      Ib_RMS   = STOF(ISTOF + 7)
      Ic_RMS   = STOF(ISTOF + 8)
      RT_1     = STOF(ISTOF + 9)
      I_Fault  = STOF(ISTOF + 10)
      Va       = STOF(ISTOF + 12)
      Vb       = STOF(ISTOF + 13)
      Vc       = STOF(ISTOF + 14)
      RT_4     = STOF(ISTOF + 16)
      RT_10    = STOF(ISTOF + 24)
      RT_12    = STOF(ISTOF + 26)
      RT_16    = STOF(ISTOF + 30)
      I_Battery = STOF(ISTOF + 37)
      RT_23    = STOF(ISTOF + 40)
      V_DC_Link = STOF(ISTOF + 41)
      RT_24    = STOF(ISTOF + 42)
      RT_26    = STOF(ISTOF + 44)
      RT_28    = STOF(ISTOF + 46)
      RT_32    = STOF(ISTOF + 50)
      RT_33    = STOF(ISTOF + 51)
      I_Train  = STOF(ISTOF + 54)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_6  = NODE(INODE + 5)
      NT_12 = NODE(INODE + 10)
      NT_13 = NODE(INODE + 11)
      NT_14 = NODE(INODE + 12)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Va = EMTDC_VVDC(SS(1), NT_12, 0)
      CALL PQVI1PH(SS(1),NT_12, (IBRCH(1)+32),RTCF(IVD1_1+2))
      RVD1_1 = RTCF(IVD1_1) * STORF(NSTORF-2)
      Pa = RVD1_1
      RVD1_1 = RTCF(IVD1_1+4) * RMS3( ( CBR((IBRCH(1)+32), SS(1))) , RTC&
     &F(IVD1_1+2) )
      Ia_RMS = RVD1_1

! 20:[pgb] Output Channel 'Current RMS phase A'

      PGB(IPGB+1) = Ia_RMS

! 30:[pgb] Output Channel 'Voltage phase A'

      PGB(IPGB+2) = Va

! 40:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Vb = EMTDC_VVDC(SS(1), NT_13, 0)
      CALL PQVI1PH(SS(1),NT_13, (IBRCH(1)+33),RTCF(IVD1_1+2))
      RVD1_1 = RTCF(IVD1_1) * STORF(NSTORF-2)
      Pb = RVD1_1
      RVD1_1 = RTCF(IVD1_1+4) * RMS3( ( CBR((IBRCH(1)+33), SS(1))) , RTC&
     &F(IVD1_1+2) )
      Ib_RMS = RVD1_1

! 50:[pgb] Output Channel 'Current RMS phase B'

      PGB(IPGB+3) = Ib_RMS

! 60:[pgb] Output Channel 'Voltage phase B'

      PGB(IPGB+4) = Vb

! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Vc = EMTDC_VVDC(SS(1), NT_14, 0)
      CALL PQVI1PH(SS(1),NT_14, (IBRCH(1)+34),RTCF(IVD1_1+2))
      RVD1_1 = RTCF(IVD1_1) * STORF(NSTORF-2)
      Pc = RVD1_1
      RVD1_1 = RTCF(IVD1_1+4) * RMS3( ( CBR((IBRCH(1)+34), SS(1))) , RTC&
     &F(IVD1_1+2) )
      Ic_RMS = RVD1_1

! 80:[pgb] Output Channel 'Current RMS phase C'

      PGB(IPGB+5) = Ic_RMS

! 90:[pgb] Output Channel 'Voltage phase C'

      PGB(IPGB+6) = Vc

! 100:[voltmeter] Voltmeter (Line - Line) 'V_DC_Link'
      V_DC_Link = EMTDC_VVDC(SS(1), NT_6, NT_1)

! 110:[ammeter] Current Meter 'I_Fault'
      I_Fault = ( CBR((IBRCH(1)+6), SS(1)))

! 120:[ammeter] Current Meter 'I_Cap_Discharge'
      I_Cap_Discharge = ( CBR((IBRCH(1)+4), SS(1)))

! 130:[pgb] Output Channel 'DC Link Voltage'

      PGB(IPGB+7) = V_DC_Link

! 140:[pgb] Output Channel 'Fault Current'

      PGB(IPGB+8) = I_Fault

! 150:[ammeter] Current Meter 'I_Train'
      I_Train = ( CBR((IBRCH(1)+1), SS(1)))

! 160:[ammeter] Current Meter 'I_Battery'
      I_Battery = ( CBR((IBRCH(1)+51), SS(1)))

! 170:[voltmeter] Voltmeter (Line - Line) 'V_Touch'
      V_Touch = EMTDC_VVDC(SS(1), NT_1, 0)

! 180:[const] Real Constant 

      RT_12 = 3.1

! 190:[const] Real Constant 

      RT_16 = 3.0

! 230:[const] Real Constant 

      RT_1 = 5.0

! 270:[const] Real Constant 

      RT_23 = 1.5

! 280:[const] Real Constant 

      RT_10 = 2.9

! 290:[const] Real Constant 

      RT_24 = 2.8

! 310:[const] Real Constant 

      RT_32 = 8.0

! 320:[const] Real Constant 

      RT_26 = 0.0

! 330:[const] Real Constant 

      RT_4 = 3.0

! 370:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (2.0 .LE. 3.9) THEN
        RT_33 = LIMIT(2.0, 3.9, V_DC_Link)
      ELSE
        RT_33 = V_DC_Link
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,2138034843,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 400:[const] Real Constant 

      RT_28 = 0.005

! 650:[breaker1] Single Phase Breaker 'BRK_Batt'
! Single phase breaker current
!

! 670:[breaker1] Single Phase Breaker 'Breaker'
! Single phase breaker current
!

! 700:[pgb] Output Channel 'Touch Voltage'

      PGB(IPGB+11) = V_Touch

! 750:[pgb] Output Channel 'Train Current'

      PGB(IPGB+15) = I_Train

! 780:[pgb] Output Channel 'Cap Discharge Current'

      PGB(IPGB+16) = I_Cap_Discharge

! 790:[pgb] Output Channel 'Battery Current'

      PGB(IPGB+17) = I_Battery

! 800:[pgb] Output Channel 'Active Power phase C'

      PGB(IPGB+18) = Pc

! 810:[breaker3] 3 Phase Breaker 'Trip_Signal'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+35), (IBRCH(1)+36), (IBRCH(1)+37),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 820:[pgb] Output Channel 'Active Power phase B'

      PGB(IPGB+19) = Pb

! 830:[pgb] Output Channel 'Active Power phase A'

      PGB(IPGB+20) = Pa

! 840:[breaker1] Single Phase Breaker 'Cmd_PreCh'
! Single phase breaker current
!

! 850:[breaker1] Single Phase Breaker 'Cmd_Main_HSCB'
! Single phase breaker current
!

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = I_Cap_Discharge
      STOF(ISTOF + 2) = V_Touch
      STOF(ISTOF + 3) = Pa
      STOF(ISTOF + 4) = Pb
      STOF(ISTOF + 5) = Pc
      STOF(ISTOF + 6) = Ia_RMS
      STOF(ISTOF + 7) = Ib_RMS
      STOF(ISTOF + 8) = Ic_RMS
      STOF(ISTOF + 9) = RT_1
      STOF(ISTOF + 10) = I_Fault
      STOF(ISTOF + 12) = Va
      STOF(ISTOF + 13) = Vb
      STOF(ISTOF + 14) = Vc
      STOF(ISTOF + 16) = RT_4
      STOF(ISTOF + 24) = RT_10
      STOF(ISTOF + 26) = RT_12
      STOF(ISTOF + 30) = RT_16
      STOF(ISTOF + 37) = I_Battery
      STOF(ISTOF + 40) = RT_23
      STOF(ISTOF + 41) = V_DC_Link
      STOF(ISTOF + 42) = RT_24
      STOF(ISTOF + 44) = RT_26
      STOF(ISTOF + 46) = RT_28
      STOF(ISTOF + 50) = RT_32
      STOF(ISTOF + 51) = RT_33
      STOF(ISTOF + 54) = I_Train


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_4, RT_10, RT_12, RT_16
      REAL     RT_23, RT_24, RT_26, RT_28, RT_32

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 57
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 180:[const] Real Constant 
      RT_12 = 3.1

! 190:[const] Real Constant 
      RT_16 = 3.0

! 200:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1164716438)
      CALL E_XSGEN1_CFG(1,0.0,50.0,1.0,0.0)

! 210:[sumjct] Summing/Differencing Junctions 

! 220:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.6
      NRTCF = NRTCF + 1

! 230:[const] Real Constant 
      RT_1 = 5.0

! 240:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,903945719)
      CALL E_XSGEN1_CFG(1,180.0,50.0,1.0,0.0)

! 250:[time-sig] Output of Simulation Time 

! 270:[const] Real Constant 
      RT_23 = 1.5

! 280:[const] Real Constant 
      RT_10 = 2.9

! 290:[const] Real Constant 
      RT_24 = 2.8

! 300:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1637781821)
      CALL E_XSGEN1_CFG(1,0.0,50.0,1.0,0.0)

! 310:[const] Real Constant 
      RT_32 = 8.0

! 320:[const] Real Constant 
      RT_26 = 0.0

! 330:[const] Real Constant 
      RT_4 = 3.0

! 340:[sumjct] Summing/Differencing Junctions 

! 350:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.6
      NRTCF = NRTCF + 1

! 360:[sumjct] Summing/Differencing Junctions 

! 380:[time-sig] Output of Simulation Time 

! 390:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,496891745)
      CALL E_XSGEN1_CFG(1,180.0,50.0,1.0,0.0)

! 400:[const] Real Constant 
      RT_28 = 0.005

! 410:[compar] Two Input Comparator 

! 420:[compar] Two Input Comparator 

! 430:[mult] Multiplier 

! 440:[delay] Binary ON Delay with Interpolation 

! 450:[compar] Two Input Comparator 

! 460:[compar] Two Input Comparator 

! 470:[compar] Two Input Comparator 

! 480:[flip_flop] Flip-Flop and latches /w Interpolation 
      CALL E_XFLIP1_CFG(2,1,0,0)

! 490:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.6
      NRTCF = NRTCF + 1

! 500:[div] Divider 

! 510:[mult] Multiplier 

! 520:[compar] Two Input Comparator 

! 530:[sumjct] Summing/Differencing Junctions 

! 540:[mult] Multiplier 

! 550:[flip_flop] Flip-Flop and latches /w Interpolation 
      CALL E_XFLIP1_CFG(2,1,0,0)

! 560:[inv] Interpolated Logic Inverter 

! 570:[realpole] Real Pole 

! 580:[compar] Two Input Comparator 

! 590:[compar] Two Input Comparator 

! 600:[inv] Interpolated Logic Inverter 

! 610:[inv] Interpolated Logic Inverter 

! 620:[compar] Two Input Comparator 

! 630:[compar] Two Input Comparator 

! 640:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 650:[breaker1] Single Phase Breaker 'BRK_Batt'
      CALL COMPONENT_ID(ICALL_NO,415900577)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 660:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 670:[breaker1] Single Phase Breaker 'Breaker'
      CALL COMPONENT_ID(ICALL_NO,926414752)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 680:[pgb] Output Channel 'g4'

! 690:[pgb] Output Channel 'g2'

! 710:[pgb] Output Channel 'Ext Current Control'

! 720:[pgb] Output Channel 'g3'

! 730:[pgb] Output Channel 'g1'

! 740:[src_ccin_1] Current Source 'I_Train'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+2),SS(1))

! 760:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 770:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 810:[breaker3] 3 Phase Breaker 'Trip_Signal'
      CALL COMPONENT_ID(ICALL_NO,1235735319)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 840:[breaker1] Single Phase Breaker 'Cmd_PreCh'
      CALL COMPONENT_ID(ICALL_NO,69880901)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 850:[breaker1] Single Phase Breaker 'Cmd_Main_HSCB'
      CALL COMPONENT_ID(ICALL_NO,1927417187)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+39),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+41),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[source_3] Three Phase Voltage Source Model 2 'AC Grid'
      RTCF(NRTCF)   = 132.0*SQRT_2*SQRT_1BY3
      RTCF(NRTCF+1) = 50.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+43),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 'T32'
      CALL COMPONENT_ID(ICALL_NO,1312675415)
      RVD1_1 = ONE_3RD*5.0
      RVD1_2 = 132.0*SQRT_1BY3
      RVD1_3 = 2.3
      CALL E_TF2W_CFG((IXFMR + 1),0,RVD1_1,50.0,0.1,0.0,RVD1_2,RVD1_3,0.&
     &4)
      CALL E_TF2W_CFG((IXFMR + 2),0,RVD1_1,50.0,0.1,0.0,RVD1_2,RVD1_3,0.&
     &4)
      CALL E_TF2W_CFG((IXFMR + 3),0,RVD1_1,50.0,0.1,0.0,RVD1_2,RVD1_3,0.&
     &4)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(5.0*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH(1)+20),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+21),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+22),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+23),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+24),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+25),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2, (IBRCH(1)+26), (IBRCH(1)+27), (IBRCH(1)+28), (IB&
     &RCH(1)+29), (IBRCH(1)+30), (IBRCH(1)+31),0,0,0,0,0,0,SS(1),RVD1_1,&
     &0.2,1.17,50.0,0.0,0.4,0.0,0.1,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD1_3,0.&
     &0,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+45),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+47),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+49),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[battery] Generic battery model 'Battery Bank'
      CALL COMPONENT_ID(ICALL_NO,54542169)
      CALL BATTERYCOEFF1_CFG(SS(1), (IBRCH(1)+12),1.2,1.15,1.03,0.416,0.&
     &95,0.4,70.0,0.005,20.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1, NT_6, NT_12, NT_13, NT_14

! Control Signals
      REAL     RT_1, RT_4, RT_10, RT_12, RT_16
      REAL     RT_23, RT_24, RT_26, RT_28, RT_32

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 57
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_6  = NODE(INODE + 5)
      NT_12 = NODE(INODE + 10)
      NT_13 = NODE(INODE + 11)
      NT_14 = NODE(INODE + 12)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 20:[pgb] Output Channel 'Current RMS phase A'

! 30:[pgb] Output Channel 'Voltage phase A'

! 40:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 50:[pgb] Output Channel 'Current RMS phase B'

! 60:[pgb] Output Channel 'Voltage phase B'

! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 80:[pgb] Output Channel 'Current RMS phase C'

! 90:[pgb] Output Channel 'Voltage phase C'

! 130:[pgb] Output Channel 'DC Link Voltage'

! 140:[pgb] Output Channel 'Fault Current'

! 180:[const] Real Constant 
      RT_12 = 3.1

! 190:[const] Real Constant 
      RT_16 = 3.0

! 230:[const] Real Constant 
      RT_1 = 5.0

! 270:[const] Real Constant 
      RT_23 = 1.5

! 280:[const] Real Constant 
      RT_10 = 2.9

! 290:[const] Real Constant 
      RT_24 = 2.8

! 310:[const] Real Constant 
      RT_32 = 8.0

! 320:[const] Real Constant 
      RT_26 = 0.0

! 330:[const] Real Constant 
      RT_4 = 3.0

! 370:[hardlimit] Hard Limiter 

! 400:[const] Real Constant 
      RT_28 = 0.005

! 700:[pgb] Output Channel 'Touch Voltage'

! 750:[pgb] Output Channel 'Train Current'

! 780:[pgb] Output Channel 'Cap Discharge Current'

! 790:[pgb] Output Channel 'Battery Current'

! 800:[pgb] Output Channel 'Active Power phase C'

! 820:[pgb] Output Channel 'Active Power phase B'

! 830:[pgb] Output Channel 'Active Power phase A'

      RETURN
      END

